### ISSUE TITLE
No such file or directory: '/dev/vmgfx32'

### ISSUE THREAD

**Issue by DennisFaucher** [thebel1/thgpio#1]
Thank you very much for the VIB.  I would like to turn the power on to my rPi4 fan. I installed your VIB successfully but when I try and run gpio_util.py, I get this error. TIA.

[root@localhost:/vmfs/volumes/3ded9637-343e1f0b/thgpio/pyUtil] python -V
Python 3.5.7
[root@localhost:/vmfs/volumes/3ded9637-343e1f0b/thgpio/pyUtil] python ./gpio_util.py level 18
Traceback (most recent call last):
  File "./gpio_util.py", line 11, in <module>
    from gpioLib import *
  File "/vmfs/volumes/3ded9637-343e1f0b/thgpio/pyUtil/gpioLib/__init__.py", line 127, in <module>
    class GPIO:
  File "/vmfs/volumes/3ded9637-343e1f0b/thgpio/pyUtil/gpioLib/__init__.py", line 128, in GPIO
    gpioDev = open(GPIO_DEVICE_PATH, 'r+b')
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vmgfx32'

**Comment by thebel1** [comment]
Hi Dennis,

Was the RPi rebooted after installing the VIB? You'll need to do that for the driver to load and create a character device file at `/dev/vmgfx32`. I've added that to the readme now.

If, after rebooting, you still can't use the util script, please run the following command and paste the output into this thread:

`zcat /var/log/boot.gz | fgrep gpio`

**Comment by thebel1** [comment]
Posting here as a reminder to myself to review the build script.

**Comment by DennisFaucher** [comment]
I did _not_ reboot. My apologies. All good and closing the issue. Thank you.

````bash
] python ./gpio_util.py level 18
0
````

**Comment by thebel1** [comment]
Glad it worked! Closing issue.
